spring.application.name=hello
server.port=8080

spring.datasource.url=jdbc:postgresql://pg-hello-poc.postgres.database.azure.com:5432/demo?sslmode=require
spring.datasource.username=hello-app-mi
spring.datasource.azure.passwordless-enabled=true
spring.cloud.azure.credential.managed-identity-enabled=true
spring.cloud.azure.credential.client-id=7c7dbd38-b3a0-49c6-a55a-27a6237645cf
